name: Deployment
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      environment_url:
        required: true
        type: string
      release:
        default: 'false'
        required: false
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
jobs:
  Deploying:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        id: vars
        run: |
          echo ::set-output name=project_version::$(cat .version)
          echo ::set-output name=ruby_version::$(cat .ruby-version)
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.0
        with:
          validation_depth: 10
          version: ${{ steps.vars.outputs.project_version }}
          path: ./CHANGELOG.md
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.vars.outputs.ruby_version }}
          bundler-cache: true
      - name: deploy
        env:
          APP_NAME: ${{ inputs.app_name }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          gem install dpl
          dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY --label=${{ steps.vars.outputs.project_version }}
      - name: Create a GitHub release
        if: ${{ inputs.release == 'true' }}
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: v${{ steps.vars.outputs.project_version }}
          name: v${{ steps.vars.outputs.project_version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
