name: Deploy Lambda Dev
on:
  workflow_call:
    inputs:
      url:
        required: false
        type: string
    secrets:
      AWS_DEV_ROLE_NAME:
        required: true
      AWS_DEV_REGION:
        required: true
jobs:
  build-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ${{ inputs.url }}
    permissions:
      id-token: write
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: SAM installation
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEV_REGION }}
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_NAME }}
      - name: SAM Build
        run: make build
      - name: SAM Deploy
        run: make deploy
      - name: Purge old cache
        uses: MyAlbum/purge-cache@v2
        with:
          debug: true
          max-age: 604800
