name: Deployment
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      environment_url:
        required: true
        type: string
      release:
        default: 'false'
        required: false
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
jobs:
  Deploying:
    runs-on: self-hosted
    container:
      image: public.ecr.aws/qflash/deployment-workflow:latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        id: vars
        run: |
          echo "project_version=$(cat .version)" >> $GITHUB_OUTPUT
      - name: Get Changelog Entry
        if: ${{ inputs.release == 'true' }}
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.vars.outputs.project_version }}
          path: ./CHANGELOG.md
      - name: Deploy to Heroku
        env:
          APP_NAME: ${{ inputs.app_name }}
          APP_VERSION: ${{ steps.vars.outputs.project_version }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY --label=$APP_VERSION --description=$APP_VERSION
      - name: Create a GitHub release
        if: ${{ inputs.release == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.vars.outputs.project_version }}
          name: v${{ steps.vars.outputs.project_version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
