name: Deployment Lambda Dev
on:
  workflow_call:
    inputs:
      url:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID_DEV:
        required: true
      AWS_SECRET_ACCESS_KEY_DEV:
        required: true
      AWS_ECR_REGION:
        required: true
jobs:
  build-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ${{ inputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: SAM installation
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}
      - name: SAM Build
        run: make build
      - name: SAM Deploy
        run: make deploy
      - name: Purge old cache
        uses: MyAlbum/purge-cache@v2
        with:
          debug: true # Purge caches by their created time (default)
          max-age: 604800 # Leave only caches accessed in the last 7 days (default)
